<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Category;
use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function findLatest($limit, Category $category = null) {
        $qb = $this->createQueryBuilder('a'); // 'a' = alias pour l'entité Article
        
        $qb
            ->orderBy('a.id', 'DESC')
            ->setMaxResults($limit)
        ;
        
        if (!is_null($category)) {
            $qb->where('IDENTITY(a.category) = ' . $category->getId());
        } // IDENTITY mot clé de Doctrine qui récupère la clé primaire sur laquelle on fait la jointure - on compare les identifiants des 
        // tables article et category
        // id clé étrangère dans article comparée avec clé primaire de la category passée en argument 2 (optionnel) de notre
        // méthode findLatest
        // même résultat avec une jointure :
        // $qb->join('a.category', 'c')
        //    ->where('c.id = '  $category->getId());
        
        return $qb->getQuery()->getResult();
    }
}
