<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Article;
use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    public function findAllByArticle(Article $article) 
    {
        // Pour avoir la connexion de Doctrine, qui est une surcharge de PDO
        // et peut s'utiliser comme PDO pour écrire les requetes SQL à la main
        // surtout si elles sont complexes
        // $cnx = $this->getEntityManager()->getConnection();
        // $cnx->
        
        $qb = $this->createQueryBuilder('c');
        
        $qb
            ->where('IDENTITY(c.article) = ' . $article->getId())
            ->orderBy('c.date', 'DESC')
        ;
                       
        return $qb->getQuery()->getResult();
    }
}
