<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Security\User\UserLoaderInterface;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository implements UserLoaderInterface
{
    public function loadUserByUsername($username) { //cette méthode va chercher l'utilisateur dans la BDD
        $qb = $this->createQueryBuilder('u'); // créé le QB de Doctrine qui permet de faire du requêtage sur la BDD en objet (avec des méthodes)
        // 'u' est l'alias dans notre table user pour faire nos requêtes
        
        $qb
            ->where('u.username = :username')
            ->orWhere('u.email = :email') //la requête permet de se connecter avec le username ou l'email
            ->setParameter('username', $username) // setParameter() fait comme bindParam()
            ->setParameter('email', $username)
        ;
        
        return $qb->getQuery()->getOneOrNullResult();
        // getQuery() nous renvoie un objet sur la requête : soit un objet QueryBuilder si tu as trouvé un résultat, soit 'null'
        // s'il ne trouve pas de résultat
        
    }
}
